= 充值金额同步到设备设计文档
v1.0, 2022-04-14
:doctype: article
:encoding: utf-8
:lang: zh
:toc:
:numbered:
:AUTHOR: wangmaojun

## 充值金额同步到设备设计

### 充值金额同步到设备设计思路

1. smface - server 关于用户的余额、补助金余额并不会真正同步到 设备上，设备上也不会缓存这些数据

2. 用户消费的时候消费机分为在线模式和记账模式

3. 在线模式的情况下，刷脸消费的时候，会显示当前余额，这个是设备发起请求调取 smface-server 接口 /request/real 查询得到的

4. 在记账模式的情况下，不会显示当前余额，不会发起关于余额查询的接口

## 程序实现流程

### request/real

====
 @PostMapping("real")
    public JSONObject real(@RequestBody JSONObject data) {
        String api = data.getString("api");
        String time = data.getString("time");
        String noncestr = data.getString("noncestr");
        String sign = data.getString("sign");
        try {
            switch (api) {
                // include balance、allowance money
                case "infoquery":
                    logger.warn("松美消费机 iorg-smface real infoquery start =================================");
                    return infoQueryService.infoQuery(data);
                default:
                logger.error("松美消费机 iorg-smface real failed =================================");
                throw new IllegalStateException("松美消费机 iorg-smface real failed, api ======================================: " + api);
            }
        } catch (Exception e) {
            logger.error("real: " + e.getMessage());
            JSONObject res = new JSONObject();
            res.put("api", api);
            res.put("result_code", "1");
            res.put("result_msg", "支付失败");
            return res;
        }
    }
====


## 修改心跳间隔时间

在服务端应答设备回传的参数可以修改心跳时间间隔，字段 interval

----
jsonObject.put("interval", 60000);
----


## 权限认证

注意：如果采用spring security 或者 Oauth2, 一定要将 /request/real 进行权限放行，不然设备无法调取接口
